### ISSUE TITLE
No toml highlighting

### ISSUE THREAD

**Issue by WhyNotHugo** [sheerun/vim-polyglot#500]
**Does this bug happen when you install plugin without vim-polyglot?**

n/a

**Describe the bug:**

I'm not getting any toml highlighting.
- `sytanx on` is set (other languages work).
- `ft` is detected as toml by itself.

**To Reproduce:**

This is my file (named `starship.toml`):
```toml
[character]
symbol = "➜"

[git_status]
show_sync_count = true

[python]
disabled = false

[aws]
disabled = true

[package]
disabled = true
```

Screenshot:

![2020-06-10T10:31:32,156110487+02:00](https://user-images.githubusercontent.com/730811/84245585-cb6ecd80-aaf4-11ea-9f7b-296840b30c5b.png)
