### ISSUE TITLE
Less syntax doesn't seem better than vim default

### ISSUE THREAD

**Issue by adrian5** [sheerun/vim-polyglot#567]
```less
@media (min-width: 768px) {
  .component {
    width: 600px;
  }
}
```

Polyglot:

1. `(min-width: 768px)` doesn't get assigned any hl-Group ❌
2. In `.component`, the `.` is `lessMixinChar` ❌

Vim default:

1. `lessCssAttribute` + `cssValueLength` + `cssUnitDecorators`  ✔
2. Dot is `lessClassChar` ✔

```less
.post a:hover {
  color: red;
  .bordered();
}
```

Polyglot:

1. `red` is `lessFunction` ❌
2. `bordered` is `lessClass` ❌

Vim default:

1. `red` is `cssColor` ✔
2. `bordered()` is `lessClassCall` ✔

---

I reckon the polyglot version handles more cases, but I'm not sure the right trade-offs were made. Vim's default left me with a better impression.

It appears that Less is pretty much dead (having lost out to Sass/SCSS), so removing it from polyglot—and falling back on the good-enough vim implementation—might be preferable.
